# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir web/serverless-microservices-web

- task: Npm@1
  inputs:
    command: 'install' # Options: install, publish, custom
    workingDir: 'web/serverless-microservices-web'
- task: Npm@1
  inputs:
    command: 'custom' # Options: install, publish, custom
    workingDir: 'web/serverless-microservices-web'
    customCommand: 'run build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 'web/serverless-microservices-web'

    Contents: 'dist/**'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'